### ISSUE TITLE
Rust: bottled binaries need resetting interpreter when installed in non-standard location

### ISSUE THREAD

**Issue by Char-Aznable** [Homebrew/linuxbrew-core#11100]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
brew install rust --force-bottle

- What happened (include command output)
Installation is successful but the binaries can't be run because the interpreter path to ld.so is hardcoded to /home/linuxbrew/.linubrew/lib/ld.so

My linuxbrew is installed in ~/.linuxbrew. I can workaround the issue using `patchelf --set-interpreter ~/.linuxbrew/opt/rust/bin/rustc` for example. Can this be done in the formula when pouring the bottle?

**Comment by sjackman** [comment]
No, I have never seen this error.

**Comment by iMichka** [comment]
```
readelf -d /home/linuxbrew/.linuxbrew/Cellar/rust/1.32.0/share/rust/rust_src/tools/lldb/unittests/ObjectFile/ELF/Inputs/early-section-headers.so
readelf: Warning: possibly corrupt ELF header - it has a non-zero program header offset, but no program headers
```

That's a test file, which is probably corrupted on purpose.

**Comment by iMichka** [comment]
I am working on a patch

**Comment by jonchang** [comment]
I'm seeing this error as well. Let me know if you need me to test anything. Not sure how to fix this.

**Comment by iMichka** [comment]
Patch is here: https://github.com/Homebrew/brew/pull/5696

I think that it stumbles on the corrupted elf file, and then does not patch the rest of the files. Can you try if it helps?

**Comment by jonchang** [comment]
@iMichka nope, doesn't seem like it. `ldd $(brew --prefix rust)/bin/cargo` still fails with `/home/jchang/.linuxbrew/bin/ldd: /home/jchang/.linuxbrew/opt/rust/bin/cargo: /home/linuxbrew/.linuxbrew/lib/ld.so: bad ELF interpreter: No such file or directory`. I checked the install log and it seems like `patchelf` worked just fine (or without an error at least)

**Comment by iMichka** [comment]
I merged https://github.com/Homebrew/brew/pull/5696. @Char-Aznable can you update, `brew uninstall rust` and `brew install rust` again?

**Comment by Char-Aznable** [comment]
I just tried it with latest bottle 1.33.0 and the problem persists.

**Comment by sjackman** [comment]
@Char-Aznable Please report `brew --version` and try `brew update`.

**Comment by Char-Aznable** [comment]
```$brew --version
Homebrew 2.0.3-41-g0f07fe5
Homebrew/linuxbrew-core (git revision f7d0dd; last commit 2019-03-11)
$ brew update
Already up-to-date.```

**Comment by kitaev-chen** [comment]
> ```
> $brew --version
> Homebrew 2.0.3-41-g0f07fe5
> Homebrew/linuxbrew-core (git revision f7d0dd; last commit 2019-03-11)
> $ brew update
> Already up-to-date.
> ```

how about your result? I think the problem still exists

**Comment by iMichka** [comment]
I does, as nobody worked on this. Pull requests are welcome though!

**Comment by sjackman** [comment]
@xu-cheng submitted PR https://github.com/Homebrew/brew/pull/6303 to fix this issue.
