### ISSUE TITLE
newsboat: Does not build on certain (Linux) systems

### ISSUE THREAD

**Issue by mglh** [Homebrew/linuxbrew-core#15586]
For me, on CentOS 7 building **newsboat 2.16.1** reproducibly fails.
Same on Debian Stretch, with partly different error message.

---

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

---

**Output of "brew install newsboat" on CentOS 7:**

```
$ brew install newsboat
==> Downloading https://newsboat.org/releases/2.16.1/newsboat-2.16.1.tar.xz
Already downloaded: /home/<USER>/.cache/Homebrew/downloads/390b536eab8c2af357937bed8a0bb2c73242153cb3e05c2fac296ccc03a772f3--newsboat-2.16.1.tar.xz
==> make install prefix=/home/<USER>/.linuxbrew/Cellar/newsboat/2.16.1
Last 15 lines from /home/<USER>/.cache/Homebrew/Logs/newsboat/01.make:
make: *** [newsboat.o] Error 1
In file included from include/view.h:11:0,
                 from include/feedlistformaction.h:8,
                 from src/colormanager.cpp:5:
include/controller.h:4:25: fatal error: libxml/tree.h: No such file or directory
compilation terminated.
make: *** [src/colormanager.o] Error 1
In file included from src/cache.cpp:14:0:
include/controller.h:4:25: fatal error: libxml/tree.h: No such file or directory
compilation terminated.
make: *** [src/cache.o] Error 1
In file included from src/htmlrenderer.cpp:15:0:
include/utils.h:5:27: fatal error: libxml/parser.h: No such file or directory
compilation terminated.
make: *** [src/htmlrenderer.o] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

$ 
```

**Output of "brew config" on CentOS 7:**

```
$ brew config
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c590d90da1c412fddd047fbb9fbd946445c4faaf
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /home/<USER>/.linuxbrew
HOMEBREW_CELLAR: /home/<USER>/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/<USER>/.cache/Homebrew
HOMEBREW_LOGS: /home/<USER>/.cache/Homebrew/Logs
HOMEBREW_REPOSITORY: /home/<USER>/.linuxbrew/Homebrew
HOMEBREW_SYSTEM_CURL_TOO_OLD: 1
CPU: 20-core 64-bit broadwell
Homebrew Ruby: 2.5.6 => /opt/ruby25/bin/ruby
Clang: 3.4 build 34
Git: 2.16.5 => /bin/git
Curl: 7.65.3 => /home/<USER>/.linuxbrew/opt/curl/bin/curl
Kernel: Linux 3.10.0-957.27.2.el7.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.6.1810 (Core)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: 2.23
gcc: 5.5.0_4
xorg: N/A
$ 
```

**Output of "brew doctor" on CentOS 7:**

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/sbin/uberspace-generate-nginx-config
  /usr/local/sbin/uberspace-generate-qmail-config

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

$ 
```

---

**Output of "brew install newsboat" on Debian Stretch:**

```
$ brew install newsboat
==> Downloading https://newsboat.org/releases/2.16.1/newsboat-2.16.1.tar.xz
Already downloaded: /home/<USER>/.cache/Homebrew/downloads/390b536eab8c2af357937bed8a0bb2c73242153cb3e05c2fac296ccc03a772f3--newsboat-2.16.1.tar.xz
==> make install prefix=/home/<USER>/.linuxbrew/Cellar/newsboat/2.16.1
Last 15 lines from /home/<USER>/.cache/Homebrew/Logs/newsboat/01.make:
Checking for package ncursesw... found
./txt2h LICENSE > xlicense.h
g++-5 -std=c++11 -O2 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/home/<USER>/.linuxbrew/Cellar/newsboat/2.16.1/share/locale\" -I/home/<USER>/.linuxbrew/Cellar/sqlite/3.29.0/include -I/home/<USER>/.linuxbrew/Cellar/curl/7.65.3/include -I/home/<USER>/.linuxbrew/Cellar/libxml2/2.9.9_2/include/libxml2 -I/home/<USER>/.linuxbrew/Cellar/libstfl/0.24_8/include -I/home/<USER>/.linuxbrew/Cellar/json-c/0.13.1/include/json-c -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/home/<USER>/.linuxbrew/Cellar/ncurses/6.1/include -I/home/<USER>/.linuxbrew/Cellar/ncurses/6.1/include/ncursesw  -o src/configcontainer.o -c src/configcontainer.cpp
g++-5 -std=c++11 -O2 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/home/<USER>/.linuxbrew/Cellar/newsboat/2.16.1/share/locale\" -I/home/<USER>/.linuxbrew/Cellar/sqlite/3.29.0/include -I/home/<USER>/.linuxbrew/Cellar/curl/7.65.3/include -I/home/<USER>/.linuxbrew/Cellar/libxml2/2.9.9_2/include/libxml2 -I/home/<USER>/.linuxbrew/Cellar/libstfl/0.24_8/include -I/home/<USER>/.linuxbrew/Cellar/json-c/0.13.1/include/json-c -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/home/<USER>/.linuxbrew/Cellar/ncurses/6.1/include -I/home/<USER>/.linuxbrew/Cellar/ncurses/6.1/include/ncursesw  -o src/configparser.o -c src/configparser.cpp
In file included from src/configcontainer.cpp:15:0:
include/utils.h:5:27: fatal error: libxml/parser.h: No such file or directory
compilation terminated.
Makefile:137: recipe for target 'src/configcontainer.o' failed
make: *** [src/configcontainer.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/configparser.cpp:16:0:
include/utils.h:5:27: fatal error: libxml/parser.h: No such file or directory
compilation terminated.
Makefile:137: recipe for target 'src/configparser.o' failed
make: *** [src/configparser.o] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

$ 
```

**Output of "brew config" on Debian Stretch:**

```
$ brew config
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c590d90da1c412fddd047fbb9fbd946445c4faaf
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /home/<USER>/.linuxbrew
HOMEBREW_CELLAR: /home/<USER>/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/<USER>/.cache/Homebrew
HOMEBREW_LOGS: /home/<USER>/.cache/Homebrew/Logs
HOMEBREW_REPOSITORY: /home/<USER>/.linuxbrew/Homebrew
CPU: dual-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /home/<USER>/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.11.0 => /usr/bin/git
Curl: 7.52.1 => /usr/bin/curl
Kernel: Linux 4.9.0-11-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 9.11 (stretch) (stretch)
Host glibc: 2.24
/usr/bin/gcc: 6.3.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A
$ 
```

**Output of "brew doctor" on Debian Stretch:**

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

$ 
```

**Comment by issyl0** [comment]
Thanks for reporting this, @mglh. I've made a change upstream in Homebrew/homebrew-core that should fix this issue: the formula was missing a `libxml2` dependency that's included with macOS.

**Comment by mglh** [comment]
On Debian Stretch building newsboat seems to succeed now.

On  CentOS 7 building newsboat still fails:

```
$ brew cleanup -s ; brew upgrade ; brew update
Already up-to-date.
$ brew install newsboat
==> Downloading https://newsboat.org/releases/2.16.1/newsboat-2.16.1.tar.xz
######################################################################## 100.0%
==> make install prefix=/home/<USER>/.linuxbrew/Cellar/newsboat/2.16.1
Last 15 lines from /home/<USER>/.cache/Homebrew/Logs/newsboat/01.make:
g++-5: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Linuxbrew/homebrew-core/issues> for instructions.
make: *** [newsboat.o] Error 4
g++-5: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Linuxbrew/homebrew-core/issues> for instructions.
make: *** [src/colormanager.o] Error 4
g++-5: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Linuxbrew/homebrew-core/issues> for instructions.
make: *** [src/rssparser.o] Error 4

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
newsboat: Does not build on certain (Linux) systems https://github.com/Homebrew/linuxbrew-core/issues/15586
$ 
```

**Comment by dawidd6** [comment]
@mglh do you use different machines for debian and centos?

**Comment by mglh** [comment]
@dawidd: yes, Debian is on my PC at home, CentOS on a remote system I use.

**Comment by dawidd6** [comment]
This error on centos seems to be related to low memory. I guess you have less memory on remote machine than the one at home.

**Comment by mglh** [comment]
I did take look on it:

```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            23G         11G        1,8G        3,1G         10G        7,7G
Swap:            0B          0B          0B
```

As far as I can see, memory is sufficent.

What else could it be?

**Comment by Minoru** [comment]
Hi, Newsboat maintainer here. Thanks for packaging my software!

1.8G of RAM might not be sufficient if you got a lot of compilation jobs running. `make` accepts `--jobs` parameter, try passing `--jobs=1`. Note that it won't affect Cargo (Rust build tool); Cargo defaults to the number of CPUs, and can be controlled via an environment variable `CARGO_BUILD_JOBS`. Not sure where to specify all that in the Homebrew recipe, hope you can figure that out.

**Comment by dawidd6** [comment]
Maybe
```ruby
ENV.deparallelize unless OS.mac?
```
would be sufficient?

**Comment by iMichka** [comment]
> g++-5: internal compiler error:

Definitively and out of memory error.

We use `ENV.deparallelize` in the following context: it does not build with multiple cores because there is a bug in the build script / makefile.

If it is an out of memory error, we prefer to use something like:
`ENV["MAKEFLAGS"] = "-j1"`

or whatever value suits you. This does not always solve all the issues though. Some linker steps can use more than 4G of RAM in some cases, and run on one core. But it may be worth a try.

This line needs to be added at the top of the `install` step of the formula.

In general we will not accept this kind of change in the formula, unless there is a really good reason for it: it would make build times slower for all the other users. So you may have to add more memory, or more swap.

**Comment by mglh** [comment]
@dawidd6, @iMichka, thank you for your help.

Meanwhile `libxml2` was added as a dependency (for Linux), 
and after temporarily adding `ENV["MAKEFLAGS"] = "-j1"` locally,
it seems to build successfully, on Debian Stretch as well as on the CentOS 7 system.

Therefor I close this issue.

**Comment by jonchang** [comment]
Generally if it's just for your own machine setting `HOMEBREW_MAKE_JOBS` may be easier than manually editing formula to set `MAKEFLAGS`. See `man brew` for more details.

**Comment by mglh** [comment]
Thank you for this hint!

I will try it the next time too little memory breaks a build on this machine.

Am 18. September 2019 03:11:54 MESZ schrieb Jonathan Chang <notifications@github.com>:
