### ISSUE TITLE
Error installing clamav -- libiconv: is not needed on Linux, where iconv.h is provided by glibc

### ISSUE THREAD

**Issue by ShellyYBlack** [Homebrew/linuxbrew-core#21544]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install clamav. I am running Ubuntu 20.04.1 via Hyper-V on a Windows 10 machine.

## What happened (include command output)

Install failed. See output below, as well as results of the checklist above.

<details>
  <summary>Command output</summary>
  <pre>

shelly@shelly-Virtual-Machine:~$ brew install clamav
libiconv: is not needed on Linux, where iconv.h is provided by glibc
Error: An unsatisfied requirement failed this build.
shelly@shelly-Virtual-Machine:~$ brew gist-logs clamav
Error: No logs.
shelly@shelly-Virtual-Machine:~$ brew doctor
Your system is ready to brew.
shelly@shelly-Virtual-Machine:~$ brew config
HOMEBREW_VERSION: 2.5.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 07b3aa69f8dc5098437cf2562864558bae2d45aa
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: a70af2c7f99a5c4a3678c5031e9a45740d86780d
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: hexa-core 64-bit skylake
Clang: N/A
Git: 2.29.2 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-48-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.1 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc: N/A
xorg: N/A

  </pre>
</details>

## What you expected to happen

Expected clamav to install.

## Step-by-step reproduction instructions (by running `brew install` commands)

See above, and thanks!

**Comment by iMichka** [comment]
I think this has been fixed by #21539

**Comment by ShellyYBlack** [comment]
Hmm, still not working. Does the [clamav formula](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/clamav.rb) need an update?

**Comment by iMichka** [comment]
Yes, right, sorry, I thought it was related to the groff issue. The clamav formula needs to be fixed, I'll have a look later, but you can also open a pull request to fix it if you want, I can guide you throgh this.

The libiconv dependency needs to be put in a on_macos do / end block. And we need to add glib as a dependency instead, inside a on_linux do / end block.

**Comment by aksyom** [comment]
I have the exact same issue. I have absolutely no expertise on brew or any of this stuff, so if you want me to fix this myself you have to provide exact instructions on what I need to do! Of course it would be nice to get this thing working without me having to do stuff I have no idea about, I really need the clamav to scan files on a server I have no root access to :S

And yes I tried manually compiling clamav from source but the damn thing will not accept home dir as prefix, it just keeps failing. The instructions provided by ClamAV to build the thing are horrible and do not give any advice on how to do local install.

**Comment by iMichka** [comment]
I was able to build it in the pull request: #21550

But I am unable to run the test that is provided by the formula. Maybe you have a better idea of what fails if it is an actual runtime bug?
